### Health Check
GET {{HostAddress}}/health

### Get User (with actor)
GET {{HostAddress}}/api/Users/xavier?api-version=2023-06-06
X-Test-Actor: {{adminActor}}
Accept: application/json

###
### Create User (with actor)
POST {{HostAddress}}/api/Users?api-version=2023-06-06
X-Test-Actor: {{adminActor}}
Content-Type: application/json

{
  "firstName": "Xavier",
  "lastName": "John",
  "email": "xavier@heaven.com",
  "password": "Super!Complex6"
}

###
### Create User - restricted user
POST {{HostAddress}}/api/Users?api-version=2023-06-06
X-Test-Actor: {{testUserActor}}
Content-Type: application/json

{
  "firstName": "Xavier",
  "lastName": "John",
  "email": "xavier@heaven.com",
  "password": "Super!Complex6"
}

###
### Bad Request - invalid email
POST {{HostAddress}}/api/Users?api-version=2023-06-06
X-Test-Actor: {{adminActor}}
Content-Type: application/json

{
  "firstName": "Xavier",
  "lastName": "John",
  "email": "xavier",
  "password": "Super!Complex6"
}

###
### Bad Request - invalid password
POST {{HostAddress}}/api/Users?api-version=2023-06-06
X-Test-Actor: {{adminActor}}
Content-Type: application/json

{
  "firstName": "Xavier",
  "lastName": "John",
  "email": "xavier@heaven.com",
  "password": "SimplePassword"
}

###
### Bad Request - multiple fields
POST {{HostAddress}}/api/Users?api-version=2023-06-06
X-Test-Actor: {{adminActor}}
Content-Type: application/json

{
  "firstName": "",
  "lastName": "",
  "email": "xavier",
  "password": "Super!Complex6"
}