name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main, release/v** ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'
        
    - name: Setup versioning
      uses: dotnet/nbgv@master
      with:
        setAllVars: true

    - name: Restore dependencies
      run: dotnet restore template/TrellisAspTemplate.slnx

    - name: Build
      run: dotnet build template/TrellisAspTemplate.slnx --no-restore -c Release

    - name: Test
      run: |
        dotnet test template/TrellisAspTemplate.slnx --no-build -c Release \
          --filter-not-trait "Category=Integration" \
          --coverage --coverage-output-format cobertura --coverage-output coverage.cobertura.xml \
          --report-trx

    - name: Pack template
      run: dotnet pack templatepack.csproj -c Release -o nupkg

    - name: Upload NuGet package
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: nuget-package
        path: nupkg/*.nupkg